const EErrors = {
    ROUTING_ERROR : 1,
    INVALID_TYPES_ERROR: 2,
    INVALID_ID_PRODUCT_ERROR: 3,
    INVALID_ID_CART_ERROR: 4,
    EMAIL_ERROR: 5,
    INVALID_ID_TICKET_ERROR: 6,
    EXISTING_CODE_ERROR: 7,
    COOKIE_NOT_FOUND_ERROR: 8
}

export default EErrors